export const modTagList = {
  CurseForge: [
    "All",
    "Addons",
    "Adventure and RPG",
    "API and Library",
    "Armor, Tools, and Weapons",
    "Bug Fixes",
    "Cosmetic",
    "Education",
    "Food",
    "Magic",
    "Map and Information",
    "MCreator",
    "Miscellaneous",
    "Performance",
    "Redstone",
    "Server Utility",
    "Storage",
    "Technology",
    "Twitch Integration",
    "Utility & QoL",
    "World Gen",
  ],
  Modrinth: [
    "All",
    "Adventure",
    "Cursed",
    "Decoration",
    "Economy",
    "Equipment",
    "Food",
    "Game Mechanics",
    "Library",
    "Magic",
    "Management",
    "Minigame",
    "Mobs",
    "Optimization",
    "Social",
    "Storage",
    "Technology",
    "Transportation",
    "Utility",
    "World Generation",
  ],
};

export const worldTagList = {
  CurseForge: [
    "All",
    "Adventure",
    "Creation",
    "Game Map",
    "Modded World",
    "Parkour",
    "Puzzle",
    "Survival",
  ],
  Modrinth: [],
};

export const resourcePackTagList = {
  CurseForge: [
    "All",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x and Higher",
    "Animated",
    "Data Packs",
    "Font Packs",
    "Medieval",
    "Miscellaneous",
    "Mod Support",
    "Modern",
    "Photo Realistic",
    "Steampunk",
    "Traditional",
  ],
  Modrinth: [
    "All",
    "8x or lower",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x or higher",
    "Audio",
    "Blocks",
    "Core Shaders",
    "Entities",
    "Environment",
    "Equipment",
    "Fonts",
    "GUI",
    "Items",
    "Locale",
    "Models",
    "Combat",
    "Cursed",
    "Decoration",
    "Modded",
    "Realistic",
    "Simplistic",
    "Themed",
    "Tweaks",
    "Utility",
    "Vanilla-like",
  ],
};

export const shaderPackTagList = {
  CurseForge: ["All", "Fantasy", "Realistic", "Vanilla"],
  Modrinth: [
    "All",
    "Cartoon",
    "Cursed",
    "Fantasy",
    "Realistic",
    "Semi-Realistic",
    "Vanilla-like",
    "Atmosphere",
    "Bloom",
    "Colored Lighting",
    "Foliage",
    "Path Tracing",
    "PBR",
    "Reflections",
    "Shadows",
  ],
};

export const modpackTagList = {
  CurseForge: [
    "All",
    "Adventure and RPG",
    "Combat / PvP",
    "Exploration",
    "Extra Large",
    "FTB Official Pack",
    "Hardcore",
    "Horror",
    "Magic",
    "Map Based",
    "Mini Game",
    "Multiplayer",
    "Quests",
    "Sci-Fi",
    "Skyblock",
    "Small / Light",
    "Tech",
    "Vanilla+",
  ],
  Modrinth: [
    "All",
    "Adventure",
    "Challenging",
    "Combat",
    "Kitchen Sink",
    "Lightweight",
    "Magic",
    "Multiplayer",
    "Optimization",
    "Quests",
    "Technology",
  ],
};

export const sortByList = {
  CurseForge: [
    "Relevancy",
    "Popularity",
    "A-Z",
    "Latest update",
    "Creation date",
    "Total downloads",
  ],
  Modrinth: ["relevance", "downloads", "follows", "updated", "newest"],
};
