export const modTagList = {
  CurseForge: [
    "All",
    "Addons",
    "Adventure and RPG",
    "API and Library",
    "Applied Energistics 2",
    "Armor, Tools, and Weapons",
    "Automation",
    "Biomes",
    "Blood Magic",
    "Buildcraft",
    "Bug Fixes",
    "Cosmetic",
    "CraftTweaker",
    "Create",
    "Dimensions",
    "Education",
    "Energy",
    "Energy, Fluid, and Item Transport",
    "Farming",
    "Food",
    "Forestry",
    "Galacticraft",
    "Genetics",
    "Industrial Craft",
    "Integrated Dynamics",
    "KubeJS",
    "Magic",
    "Map and Information",
    "MCreator",
    "Miscellaneous",
    "Mobs",
    "Ores and Resources",
    "Performance",
    "Player Transport",
    "Processing",
    "Redstone",
    "Server Utility",
    "Skyblock",
    "Storage",
    "Structures",
    "Technology",
    "Thaumcraft",
    "Thermal Expansion",
    "Tinker's Construct",
    "Twilight Forest",
    "Twitch Integration",
    "Utility & QoL",
    "World Gen",
  ],
  Modrinth: [
    "All",
    "adventure",
    "cursed",
    "decoration",
    "economy",
    "equipment",
    "food",
    "game-mechanics",
    "library",
    "magic",
    "management",
    "minigame",
    "mobs",
    "optimization",
    "social",
    "storage",
    "technology",
    "transportation",
    "utility",
    "worldgen",
  ],
};

export const worldTagList = {
  CurseForge: [
    "All",
    "Adventure",
    "Creation",
    "Game Map",
    "Modded World",
    "Parkour",
    "Puzzle",
    "Survival",
  ],
  Modrinth: [],
};

export const resourcePackTagList = {
  CurseForge: [
    "All",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x and Higher",
    "Animated",
    "Data Packs",
    "Font Packs",
    "Medieval",
    "Miscellaneous",
    "Mod Support",
    "Modern",
    "Photo Realistic",
    "Steampunk",
    "Traditional",
  ],
  Modrinth: [
    "All",
    "8x-",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x+",
    "audio",
    "blocks",
    "core-shaders",
    "entities",
    "environment",
    "equipment",
    "fonts",
    "gui",
    "items",
    "locale",
    "models",
    "combat",
    "cursed",
    "decoration",
    "modded",
    "realistic",
    "simplistic",
    "themed",
    "tweaks",
    "utility",
    "vanilla-like",
  ],
};

export const shaderPackTagList = {
  CurseForge: ["All", "Fantasy", "Realistic", "Vanilla"],
  Modrinth: [
    "All",
    "cartoon",
    "cursed",
    "fantasy",
    "realistic",
    "semi-realistic",
    "vanilla-like",
    "atmosphere",
    "bloom",
    "colored-lighting",
    "foliage",
    "path-tracing",
    "pbr",
    "reflections",
    "shadows",
    "potato",
    "low",
    "medium",
    "high",
    "screenshot",
  ],
};

export const datapackTagList = {
  CurseForge: [
    "All",
    "Magic",
    "Miscellaneous",
    "Fantasy",
    "Mod Support",
    "Tech",
    "Library",
    "Utility",
    "Adventure",
  ],
  Modrinth: [
    "All",
    "adventure",
    "cursed",
    "decoration",
    "economy",
    "equipment",
    "food",
    "game-mechanics",
    "library",
    "magic",
    "management",
    "minigame",
    "mobs",
    "optimization",
    "social",
    "storage",
    "technology",
    "transportation",
    "utility",
    "worldgen",
  ], // the same as mod tag list
};

export const modpackTagList = {
  CurseForge: [
    "All",
    "Adventure and RPG",
    "Combat / PvP",
    "Exploration",
    "Extra Large",
    "FTB Official Pack",
    "Hardcore",
    "Horror",
    "Magic",
    "Map Based",
    "Mini Game",
    "Multiplayer",
    "Quests",
    "Sci-Fi",
    "Skyblock",
    "Small / Light",
    "Tech",
    "Vanilla+",
  ],
  Modrinth: [
    "All",
    "adventure",
    "challenging",
    "combat",
    "kitchen-sink",
    "lightweight",
    "magic",
    "multiplayer",
    "optimization",
    "quests",
    "technology",
  ],
};

export const sortByLists = {
  CurseForge: [
    "Popularity",
    "A-Z",
    "Latest update",
    "Creation date",
    "Total downloads",
  ],
  Modrinth: ["relevance", "downloads", "follows", "updated", "newest"],
};
