export const modTagList = {
  CurseForge: [
    "All",
    "Addons",
    "Adventure and RPG",
    "API and Library",
    "Armor, Tools, and Weapons",
    "Bug Fixes",
    "Cosmetic",
    "Education",
    "Food",
    "Magic",
    "Map and Information",
    "MCreator",
    "Miscellaneous",
    "Performance",
    "Redstone",
    "Server Utility",
    "Storage",
    "Technology",
    "Twitch Integration",
    "Utility & QoL",
    "World Gen",
  ],
  Modrinth: [
    "All",
    "adventure",
    "cursed",
    "decoration",
    "economy",
    "equipment",
    "food",
    "game-mechanics",
    "library",
    "magic",
    "management",
    "minigame",
    "mobs",
    "optimization",
    "social",
    "storage",
    "technology",
    "transportation",
    "utility",
    "worldgen",
  ],
};

export const worldTagList = {
  CurseForge: [
    "All",
    "Adventure",
    "Creation",
    "Game Map",
    "Modded World",
    "Parkour",
    "Puzzle",
    "Survival",
  ],
  Modrinth: [],
};

export const resourcePackTagList = {
  CurseForge: [
    "All",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x and Higher",
    "Animated",
    "Data Packs",
    "Font Packs",
    "Medieval",
    "Miscellaneous",
    "Mod Support",
    "Modern",
    "Photo Realistic",
    "Steampunk",
    "Traditional",
  ],
  Modrinth: [
    "All",
    "8x-",
    "16x",
    "32x",
    "64x",
    "128x",
    "256x",
    "512x+",
    "audio",
    "blocks",
    "core-shaders",
    "entities",
    "environment",
    "equipment",
    "fonts",
    "gui",
    "items",
    "locale",
    "models",
    "combat",
    "cursed",
    "decoration",
    "modded",
    "realistic",
    "simplistic",
    "themed",
    "tweaks",
    "utility",
    "vanilla-like",
  ],
};

export const shaderPackTagList = {
  CurseForge: ["All", "Fantasy", "Realistic", "Vanilla"],
  Modrinth: [
    "All",
    "cartoon",
    "cursed",
    "fantasy",
    "realistic",
    "semi-realistic",
    "vanilla-like",
    "atmosphere",
    "bloom",
    "colored-lighting",
    "foliage",
    "path-tracing",
    "pbr",
    "reflections",
    "shadows",
  ],
};

export const datapackTagList = {
  CurseForge: [
    "All",
    "Magic",
    "Miscellaneous",
    "Fantasy",
    "Mod Support",
    "Tech",
    "Library",
    "Utility",
    "Adventure",
  ],
  Modrinth: [
    "All",
    "adventure",
    "cursed",
    "decoration",
    "economy",
    "equipment",
    "food",
    "game-mechanics",
    "library",
    "magic",
    "management",
    "minigame",
    "mobs",
    "optimization",
    "social",
    "storage",
    "technology",
    "transportation",
    "utility",
    "worldgen",
  ], // the same as mod tag list
};

export const modpackTagList = {
  CurseForge: [
    "All",
    "Adventure and RPG",
    "Combat / PvP",
    "Exploration",
    "Extra Large",
    "FTB Official Pack",
    "Hardcore",
    "Horror",
    "Magic",
    "Map Based",
    "Mini Game",
    "Multiplayer",
    "Quests",
    "Sci-Fi",
    "Skyblock",
    "Small / Light",
    "Tech",
    "Vanilla+",
  ],
  Modrinth: [
    "All",
    "adventure",
    "challenging",
    "combat",
    "kitchen-sink",
    "lightweight",
    "magic",
    "multiplayer",
    "optimization",
    "quests",
    "technology",
  ],
};

export const sortByList = {
  CurseForge: [
    "Relevancy",
    "Popularity",
    "A-Z",
    "Latest update",
    "Creation date",
    "Total downloads",
  ],
  Modrinth: ["relevance", "downloads", "follows", "updated", "newest"],
};
